### ISSUE TITLE
wafer的cos图片域名是不是有bug？

### ISSUE THREAD

**Issue by yoohan-dex** [tencentyun/weapp-solution#30]
![image](https://user-images.githubusercontent.com/7565496/33243393-86f02b26-d320-11e7-9d90-03463bb0a3fc.png)
返回的url那个region变成了undefined

然后我看了源码
![image](https://user-images.githubusercontent.com/7565496/33243515-c7db834a-d322-11e7-9a82-add47bb9f422.png)
这个url跟实际的差很多 region map是没有必要的

是有别的用意吗？

**Comment by wooley** [comment]
是有问题的，我用的上海的，加了一句
const regionMap = {
    'ap-beijing-1': 'tj',
    'ap-beijing': 'bj',
    'ap-shanghai': 'sh',
    'ap-guangzhou': 'gz',
    'ap-chengdu': 'cd',
    'ap-singapore': 'sgp',
    'ap-hongkong': 'hk',
    'na-toronto': 'ca',
    'eu-frankfurt': 'ger',
    'cn-east': 'sh'
}
上传，要用cn-开头这种，读取有要用ap-shanghai,这样。
这样改最简单，也可以多加个参数，上传和下载分开两个配置。

**Comment by jas0ncn** [comment]
您升级一下wafer-node-sdk到1.1.1版本以上哈

**Comment by wooley** [comment]
实际上，如果COS使用自己绑定的域名，这块可以重写。直接用自己的静态二级域名 cos.XXX.com这样就好了。

**Comment by jas0ncn** [comment]
cos不存在绑定二级域名这种操作，您说的应该是CDN吧？sdk的返回包含了很多信息，也包含文件名，可以通过文件名和您自己的cdn域名拼出图片地址

**Comment by liuyujie-tx** [comment]
http://mirrors.tencentyun.com/npm/  这个源里最新的1.0.6？？？？？？？
能否靠谱点
