### ISSUE TITLE
信道连接问题请教

### ISSUE THREAD

**Issue by jacksplwxy** [tencentyun/weapp-solution#31]
1.如何检测当前是否有已连接的信道？
2.信道断开后怎样在保持信道ID不变的前提下进行重新连接？
3.为什么有时候会出现信道断开的情况？是系统有默认超时的原因吗？

**Comment by jas0ncn** [comment]
1. 已连接的信道需要自己进行判断
2. 断线重连就需要重新获取信道 ID 和信道地址了
3. 信道断开可能是因为网络不稳定等原因

**Comment by jacksplwxy** [comment]
关于第2点，断线就要重新获取ID，也就是没有重新连接一说，那监听reconnecting是什么情况下才会触发？

**Comment by jacksplwxy** [comment]
才明白，断线后会自动尝试重连，多次重连失败后变成error
