### ISSUE TITLE
信道服务是不是只能处理用户主动的断开请求？

### ISSUE THREAD

**Issue by Bluebang** [tencentyun/weapp-solution#33]
例如断网，崩溃这样的情况。业务服务器是收不到信道服务器推送的链接断开的请求的。是不是只能在每次推送的回调里面处理失效的链接？？

**Comment by jas0ncn** [comment]
是的

**Comment by jacksplwxy** [comment]
测试wafer2-startup的信道发现如下问题：
  客户端断网情况下，会发起重连，立刻联网即新建一个新信道ID，这样就导致在业务服务器的useMap中存储两个信道ID。请问业务服务器端如何清理掉断网之前的信道ID？
  开始以为用tunnel.broadcast的回调可以去掉断线前的信道，实际测试发现不行。后来在文档中发现onTunnelClose()方法可以监听客户端与信道服务器连接是否断线，但是不知道具体如何使用，自己测试监听不到前端断线情况。

**Comment by jas0ncn** [comment]
广播之后会返回一个无效信道ID的列表，业务方手动清除即可
