### ISSUE TITLE
小程序获取用户信息接口调整

### ISSUE THREAD

**Issue by zsh1995** [tencentyun/weapp-solution#40]
小程序获取用户信息接口调整，sdk中也有用到wx.getUserInfo

**Comment by mgsweet** [comment]
说的4月30号全面停禁，但其实到今天才发现wx.getUserInfo会稳定抛出`ERR_WX_GET_USER_INFO`，sdk中用到`wx.getUserInfo`是用不了了，所以整个wafer2只能入门到放弃了？为了弄懂这套实在花了不少时间，文档又极乱，新旧文档不一致（腾讯云上的文档竟然要比GITHUB上的要新？？？），那现在为了获取用户信息（open_id）只能让用户每次都点按钮？极其不人性化影响体验

**Comment by 1983cc** [comment]
只能等腾讯更新了wafer了吧

**Comment by mgsweet** [comment]
@1983cc 强行且代码极其恶心地改了还是可以用的

**Comment by jas0ncn** [comment]
我们已经在处理这个问题了，预计下周发布新版本修复这个问题。

**Comment by jas0ncn** [comment]
已经修复这个问题啦，欢迎大家下载新版的 Demo 和 SDK 体验
